apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2019-02-12T01:18:54Z"
  name: access-log-template
  namespace: default
  resourceVersion: "1475754"
  selfLink: /api/v1/namespaces/default/configmaps/access-log-template
  uid: 29adf22b-2e64-11e9-9d14-0afca8056c50
data:
  access_log_template.json: |
    {
      "index_patterns": ["webapp.access.logs*"],
      "settings": {
        "number_of_shards": 5
      },
      "mappings": {
        "_doc": {
          "properties": {
            "type": { "type": "keyword" },
            "location_array": { "type": "geo_point" },
            "location_properties": { "type": "geo_point" },
            "location_string": { "type": "geo_point" },
            "duration": { "type": "double" },
            "size": { "type": "long" }
          }
        }
      }
    }
