kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: admins
subjects:
-  kind: Group
   name: 4xlabs
   apiGroup: rbac.authorization.k8s.io
roleRef:
   kind: ClusterRole
   name: admin
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::699575179986:role/eksctl-iconverse-nodegroup-ng-ico-NodeInstanceRole-19ZD4MCF2AL96
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::699575179986:role/eksctl-iconverse-nodegroup-ng-ico-NodeInstanceRole-1TMTGWB8ZAUE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::699575179986:role/eksctl-iconverse-nodegroup-ng-ico-NodeInstanceRole-77B4JNL69SXX
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::699575179986:role/eksctl-iconverse-cluster-ServiceRole-IEMMX9SM4EJH
      groups:
        - 4xlabs
    - rolearn: arn:aws:iam::699575179986:role/EKSOpsAdmin
      username: eksopsadmin
      groups: 
        - system:masters
