apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2019-07-05T08:46:00Z"
  name: biz4x-secret
  namespace: default
  resourceVersion: "2692503"
  selfLink: /api/v1/namespaces/default/secrets/tmp
  uid: 348fc84b-97d9-426f-a691-4f09c77c852f
type: Opaque
data:
  biz4x-config.json: ewogICAgIkJhY2tlbmRTZXJ2ZXJVcmwiOiAic3ZjLWJpejR4YmFja2VuZDo1MDAyIiwKICAgICJDb25uZWN0aW9uU3RyaW5ncyI6IHsKICAgICAgICAiRGVmYXVsdENvbm5lY3Rpb24iOiAiU2VydmVyPXN2Yy1teXNxbDtEYXRhYmFzZT1iaXo0eGRiO3VzZXI9Z3Vlc3Q7cGFzc3dvcmQ9UEAkJHcwcmQiLAogICAgICAgICJHZXQ0eENvbm5lY3Rpb24iOiAiU2VydmVyPXN2Yy1teXNxbDtEYXRhYmFzZT1nZXQ0eC0xNjA5MDg7dXNlcj1ndWVzdDtwYXNzd29yZD1QQCQkdzByZDtjaGFyc2V0PXV0Zjg7UG9ydD0zMzA2O0RlZmF1bHQgQ29tbWFuZCBUaW1lb3V0PTMwMDsiLAogICAgICAgICJMb2dEYkNvbm5lY3Rpb24iOiAiU2VydmVyPXN2Yy1teXNxbDtEYXRhYmFzZT1iaXo0eF9kZXZfbG9nO3VzZXI9Z3Vlc3Q7cGFzc3dvcmQ9UEAkJHcwcmQ7Y2hhcnNldD11dGY4O1BvcnQ9MzMwNjtEZWZhdWx0IENvbW1hbmQgVGltZW91dD0zMDA7IgogICAgfQp9Cg==
