apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: biz4x-frontend
  labels:
    app: biz4x-frontend
    component: biz4x
spec:
  serviceName: svc-biz4xfrontend
  podManagementPolicy: "Parallel" # Default is OrderedReady
  replicas: 2 # Default is 1
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: biz4x-frontend # Has to match .spec.template.metadata.labels
      component: biz4x
  template:
    metadata:
      labels:
        app: biz4x-frontend # Has to match .spec.selector.matchLabels
        component: biz4x
    spec:
      terminationGracePeriodSeconds: 10
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - biz4x-frontend
#            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: biz4x-frontend
        image: 699575179986.dkr.ecr.ap-southeast-1.amazonaws.com/biz4x-frontend:latest
        imagePullPolicy: Always
        env:    
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:5001"
        ports:
        - containerPort: 5001
          name: http
          protocol: TCP
#          hostPort: 8081
        - containerPort: 443
          name: https
          protocol: TCP
#          hostPort: 8082
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 20
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: biz4x-secret
          mountPath: /app/appsettings.secret.json
          subPath: appsettings.secret.json
          readOnly: true
        resources:
          limits:
            cpu: 250m
            memory: 1024Mi
#      - name: fluentd
#        image: khteh/fluentd:latest
#        env:
#        - name: FLUENTD_ARGS
#          value: -c /etc/td-agent/td-agent.conf
#        volumeMounts:
#        - name: tomcat-log
#          mountPath: /usr/local/tomcat/logs
#        - name: fluentd-config
#          mountPath: /etc/td-agent
#        - name: access-log-template
#          mountPath: /tmp/access_log_template.json
#          subPath: access_log_template.json
#          readOnly: true
#        resources:
#          limits:
#            cpu: 250m
#            memory: 1024Mi
      volumes:
      - name: biz4x-secret
        secret:
          secretName: biz4x-secret
          items:  
          - key: biz4x-secret.json
            path: appsettings.secret.json
#      - name: fluentd-config
#        configMap:
#          name: fluentd-config
#      - name: access-log-template
#        configMap:
#          name: access-log-template
#      - name: tomcat-log
#        emptyDir: {}
