apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: biz4x-backend
  labels:
    app: biz4x-backend
    component: biz4x
spec:
  serviceName: svc-biz4xbackend
  podManagementPolicy: "Parallel" # Default is OrderedReady
  replicas: 2 # Default is 1
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: biz4x-backend # Has to match .spec.template.metadata.labels
      component: biz4x
  template:
    metadata:
      labels:
        app: biz4x-backend # Has to match .spec.selector.matchLabels
        component: biz4x
    spec:
      terminationGracePeriodSeconds: 10
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - biz4x-backend
#            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: biz4x-backend
        image: 699575179986.dkr.ecr.ap-southeast-1.amazonaws.com/biz4x-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
          name: http
          protocol: TCP
#          hostPort: 8081
        - containerPort: 443
          name: https
          protocol: TCP
#          hostPort: 8082
        volumeMounts:
        - name: mysql-connection
          mountPath: /app/appsettings.mysql.json
          subPath: appsettings.mysql.json
          readOnly: true
        resources:
          limits:
            cpu: 250m
            memory: 1024Mi
#      - name: fluentd
#        image: khteh/fluentd:latest
#        env:
#        - name: FLUENTD_ARGS
#          value: -c /etc/td-agent/td-agent.conf
#        volumeMounts:
#        - name: tomcat-log
#          mountPath: /usr/local/tomcat/logs
#        - name: fluentd-config
#          mountPath: /etc/td-agent
#        - name: access-log-template
#          mountPath: /tmp/access_log_template.json
#          subPath: access_log_template.json
#          readOnly: true
#        resources:
#          limits:
#            cpu: 250m
#            memory: 1024Mi
      volumes:
      - name: mysql-connection
        secret:
          secretName: biz4xdb-secret
#      - name: fluentd-config
#        configMap:
#          name: fluentd-config
#      - name: access-log-template
#        configMap:
#          name: access-log-template
#      - name: tomcat-log
#        emptyDir: {}
