apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: daemonset
  name: daemonset
spec:
  selector:
    matchLabels:
      name: daemonset
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      hostPID: true
      containers:
      - name: daemonset
        image: gcr.io/google-containers/startup-script:v2
        imagePullPolicy: IfNotPresent
#        securityContext:
#          privileged: true
        env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            set -x
            sysctl -w vm.max_map_count=262144
            sysctl -w net.core.somaxconn=1024
            sysctl -w net.core.netdev_max_backlog=5000
            sysctl -w net.core.rmem_max=16777216
            sysctl -w net.core.wmem_max=16777216
            sysctl -w net.ipv4.tcp_wmem="4096 12582912 16777216"
            sysctl -w net.ipv4.tcp_rmem="4096 12582912 16777216"
            sysctl -w net.ipv4.tcp_max_syn_backlog=8096
            sysctl -w net.ipv4.tcp_slow_start_after_idle=0
            sysctl -w net.ipv4.tcp_tw_reuse=1
            sysctl -w net.ipv4.ip_local_port_range="10240 65535"
            echo "done"
