apiVersion: v1
kind: Service
metadata:
  name: svc-elasticsearch
  labels:
    app: app-elasticsearch
spec:
  ports:
  - port: 9100
    name: elasticsearch
  clusterIP: None # Headless
  selector:
    app: app-elasticsearch
#    tier: database
