apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-init
  labels: 
    component: elasticsearch
spec:
#  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: elasticsearch-init-job
        image: khteh/elasticsearch-init:latest
        volumeMounts:
        - name: access-log-template
          mountPath: /tmp
          readOnly: true
      volumes:
      - name: access-log-template
        configMap:
          name: access-log-template
