apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2018-12-28T04:09:38Z"
  name: elasticsearch-config
  namespace: default
  resourceVersion: "789954"
  selfLink: /api/v1/namespaces/default/configmaps/elasticsearch-config
  uid: 6494f746-0a56-11e9-a34a-482ae31e6a94
data:
  elasticsearch-master.yml: |+
    cluster.name: elasticsearch
    cluster.initial_master_nodes: 
      - elasticsearch-master-0
      - elasticsearch-master-1
      - elasticsearch-master-2
    discovery.seed_hosts:
      - elasticsearch-master-0.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-1.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-2.svc-elasticsearch-discovery.default.svc.cluster.local:9300
    script.painless.regex.enabled: true
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    network.host: _site_
    node.name: ${HOSTNAME}
    node.master: true
    node.data: false
    bootstrap.memory_lock: true

  elasticsearch-data.yml: |+
    cluster.name: elasticsearch
    cluster.initial_master_nodes: 
      - elasticsearch-master-0
      - elasticsearch-master-1
      - elasticsearch-master-2
    discovery.seed_hosts:
      - elasticsearch-master-0.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-1.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-2.svc-elasticsearch-discovery.default.svc.cluster.local:9300
    script.painless.regex.enabled: true
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    network.host: _site_
    node.name: ${HOSTNAME}
    node.master: false
    node.data: true
    bootstrap.memory_lock: true

  ES_JAVA_OPTS: -Xms512m -Xmx512m -Djna.tmpdir=/tmp
