apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/app-root: /
#    nginx.ingress.kubernetes.io/affinity: "cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "ingress-cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "route"
#    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
#    nginx.ingress.kubernetes.io/session-cookie-expires: "600"
#    nginx.ingress.kubernetes.io/session-cookie-max-age: "600"
#    certmanager.k8s.io/issuer: "iconverse-letsencrypt"
#    certmanager.k8s.io/acme-challenge-type: http01
#    kubernetes.io/tls-acme: 'true'
  labels:
    app: ingress
spec:
#  tls:
#  - hosts:
#    - iconverse-k8s.taiger.io
#    secretName: iconverse-k8s.tls
  rules:  
    - host:
      http: 
        paths:
          - path: /apistarter(/|$)(.*)
            backend:
#              serviceName: svc-aspnetapistarter-ingress
              serviceName: svc-aspnetapistarter
              servicePort: 5000
          - path: //apistarter(/|$)(.*)
            backend:
#              serviceName: svc-aspnetapistarter-ingress
              serviceName: svc-aspnetapistarter
              servicePort: 5000
          - path: /biz4x(/|$)(.*)
            backend:
#              serviceName: svc-biz4xfrontend-ingress
              serviceName: svc-biz4xfrontend
              servicePort: 5001
          - path: //biz4x(/|$)(.*)
            backend:
#              serviceName: svc-biz4xfrontend-ingress
              serviceName: svc-biz4xfrontend
              servicePort: 5001
          - path: /kibana(/|$)(.*)
            backend:
#              serviceName: svc-kibana-ingress
              serviceName: svc-kibana
              servicePort: 5601
          - path: //kibana(/|$)(.*)
            backend:
#              serviceName: svc-kibana-ingress
              serviceName: svc-kibana
              servicePort: 5601
