apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: VGFpZ2VyU2luZ2Fwb3JlMTIzKg==
  mysql-user: aWNvbnZlcnNl
  mysql-password: VGFpZ2VyU2luZ2Fwb3JlMTIzKg==
