apiVersion: v1
kind: Service 
metadata:
  name: svc-mysql
  labels: 
    app: db-mysql
spec:
  selector:
    app: db-mysql
#    tier: database
  ports:  
  - port: 3306
    name: mysql
  clusterIP: None # Headless
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "svc-mysql"
  podManagementPolicy: "Parallel" # Default is OrderedReady
  replicas: 1 # Default is 1
  selector:
    matchLabels:
      app: db-mysql # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: db-mysql # Has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
#        image: mysql:latest
        image: khteh/database:mysql
        imagePullPolicy: Always
#        command: ["mysqld"]
#        args: ["--lower_case_table_names=1", "--skip-ssl", "--ignore-db-dir=lost+found"]
        env:
#         - name: MYSQL_ALLOW_EMPTY_PASSWORD
#           value: "1"
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-root-password
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-user
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-password
         - name: MYSQL_DATABASE
           value: iconverse
         - name: MYSQL_DATABASE_1
           value: book
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysqlinit
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
