apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2019-06-16T11:31:31Z"
  name: mysqlinit
  namespace: default
  resourceVersion: "727488"
  selfLink: /api/v1/namespaces/default/configmaps/mysqlinit
  uid: 49e034bc-902a-11e9-9982-e86a64ff2841
data:
  AspNetCoreApiStarter.sql: "-- MySQL dump 10.13  Distrib 8.0.16, for Linux
    (x86_64)\n--\n-- Host: localhost    Database: AspNetCoreApiStarter\n-- ------------------------------------------------------\n--
    Server version\t8.0.16\n\n/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT
    */;\n/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n/*!40101
    SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n SET NAMES utf8mb4 ;\n/*!40103
    SET @OLD_TIME_ZONE=@@TIME_ZONE */;\n/*!40103 SET TIME_ZONE='+00:00' */;\n/*!40014
    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;\n/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS=0 */;\n/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO'
    */;\n/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;\n\n--\n-- Table
    structure for table `AspNetRoleClaims`\n--\n\nDROP TABLE IF EXISTS `AspNetRoleClaims`;\n/*!40101
    SET @saved_cs_client     = @@character_set_client */;\n SET character_set_client
    = utf8mb4 ;\nCREATE TABLE `AspNetRoleClaims` (\n  `Id` int(11) NOT NULL AUTO_INCREMENT,\n
    \ `RoleId` varchar(85) NOT NULL,\n  `ClaimType` text,\n  `ClaimValue` text,\n
    \ PRIMARY KEY (`Id`),\n  KEY `IX_AspNetRoleClaims_RoleId` (`RoleId`),\n  CONSTRAINT
    `FK_AspNetRoleClaims_AspNetRoles_RoleId` FOREIGN KEY (`RoleId`) REFERENCES `AspNetRoles`
    (`Id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101
    SET character_set_client = @saved_cs_client */;\n\n--\n-- Table structure for
    table `AspNetRoles`\n--\n\nDROP TABLE IF EXISTS `AspNetRoles`;\n/*!40101 SET @saved_cs_client
    \    = @@character_set_client */;\n SET character_set_client = utf8mb4 ;\nCREATE
    TABLE `AspNetRoles` (\n  `Id` varchar(85) NOT NULL,\n  `Name` varchar(256) DEFAULT
    NULL,\n  `NormalizedName` varchar(85) DEFAULT NULL,\n  `ConcurrencyStamp` text,\n
    \ PRIMARY KEY (`Id`),\n  UNIQUE KEY `RoleNameIndex` (`NormalizedName`)\n) ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Table structure for table `AspNetUserClaims`\n--\n\nDROP
    TABLE IF EXISTS `AspNetUserClaims`;\n/*!40101 SET @saved_cs_client     = @@character_set_client
    */;\n SET character_set_client = utf8mb4 ;\nCREATE TABLE `AspNetUserClaims` (\n
    \ `Id` int(11) NOT NULL AUTO_INCREMENT,\n  `UserId` varchar(85) NOT NULL,\n  `ClaimType`
    text,\n  `ClaimValue` text,\n  PRIMARY KEY (`Id`),\n  KEY `IX_AspNetUserClaims_UserId`
    (`UserId`),\n  CONSTRAINT `FK_AspNetUserClaims_AspNetUsers_UserId` FOREIGN KEY
    (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE\n) ENGINE=InnoDB
    AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101
    SET character_set_client = @saved_cs_client */;\n\n--\n-- Table structure for
    table `AspNetUserLogins`\n--\n\nDROP TABLE IF EXISTS `AspNetUserLogins`;\n/*!40101
    SET @saved_cs_client     = @@character_set_client */;\n SET character_set_client
    = utf8mb4 ;\nCREATE TABLE `AspNetUserLogins` (\n  `LoginProvider` varchar(85)
    NOT NULL,\n  `ProviderKey` varchar(85) NOT NULL,\n  `ProviderDisplayName` text,\n
    \ `UserId` varchar(85) NOT NULL,\n  PRIMARY KEY (`LoginProvider`,`ProviderKey`),\n
    \ KEY `IX_AspNetUserLogins_UserId` (`UserId`),\n  CONSTRAINT `FK_AspNetUserLogins_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE\n) ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Table structure for table `AspNetUserRoles`\n--\n\nDROP
    TABLE IF EXISTS `AspNetUserRoles`;\n/*!40101 SET @saved_cs_client     = @@character_set_client
    */;\n SET character_set_client = utf8mb4 ;\nCREATE TABLE `AspNetUserRoles` (\n
    \ `UserId` varchar(85) NOT NULL,\n  `RoleId` varchar(85) NOT NULL,\n  PRIMARY
    KEY (`UserId`,`RoleId`),\n  KEY `IX_AspNetUserRoles_RoleId` (`RoleId`),\n  CONSTRAINT
    `FK_AspNetUserRoles_AspNetRoles_RoleId` FOREIGN KEY (`RoleId`) REFERENCES `AspNetRoles`
    (`Id`) ON DELETE CASCADE,\n  CONSTRAINT `FK_AspNetUserRoles_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE\n) ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Table structure for table `AspNetUserTokens`\n--\n\nDROP
    TABLE IF EXISTS `AspNetUserTokens`;\n/*!40101 SET @saved_cs_client     = @@character_set_client
    */;\n SET character_set_client = utf8mb4 ;\nCREATE TABLE `AspNetUserTokens` (\n
    \ `UserId` varchar(85) NOT NULL,\n  `LoginProvider` varchar(85) NOT NULL,\n  `Name`
    varchar(85) NOT NULL,\n  `Value` text,\n  PRIMARY KEY (`UserId`,`LoginProvider`,`Name`),\n
    \ CONSTRAINT `FK_AspNetUserTokens_AspNetUsers_UserId` FOREIGN KEY (`UserId`) REFERENCES
    `AspNetUsers` (`Id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client = @saved_cs_client
    */;\n\n--\n-- Table structure for table `AspNetUsers`\n--\n\nDROP TABLE IF EXISTS
    `AspNetUsers`;\n/*!40101 SET @saved_cs_client     = @@character_set_client */;\n
    SET character_set_client = utf8mb4 ;\nCREATE TABLE `AspNetUsers` (\n  `Id` varchar(85)
    NOT NULL,\n  `UserName` varchar(256) DEFAULT NULL,\n  `NormalizedUserName` varchar(256)
    DEFAULT NULL,\n  `Email` varchar(256) DEFAULT NULL,\n  `NormalizedEmail` varchar(256)
    DEFAULT NULL,\n  `EmailConfirmed` smallint(6) NOT NULL,\n  `PasswordHash` text,\n
    \ `SecurityStamp` text,\n  `ConcurrencyStamp` text,\n  `PhoneNumber` text,\n  `PhoneNumberConfirmed`
    smallint(6) NOT NULL,\n  `TwoFactorEnabled` smallint(6) NOT NULL,\n  `LockoutEnd`
    timestamp NULL DEFAULT NULL,\n  `LockoutEnabled` smallint(6) NOT NULL,\n  `AccessFailedCount`
    int(11) NOT NULL,\n  `FirstName` text,\n  `LastName` text,\n  PRIMARY KEY (`Id`),\n
    \ UNIQUE KEY `UserNameIndex` (`NormalizedUserName`),\n  KEY `EmailIndex` (`NormalizedEmail`)\n)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET
    character_set_client = @saved_cs_client */;\n\n--\n-- Table structure for table
    `IdentityUser`\n--\n\nDROP TABLE IF EXISTS `IdentityUser`;\n/*!40101 SET @saved_cs_client
    \    = @@character_set_client */;\n SET character_set_client = utf8mb4 ;\nCREATE
    TABLE `IdentityUser` (\n  `Id` varchar(85) NOT NULL,\n  `UserName` text,\n  `NormalizedUserName`
    varchar(85) DEFAULT NULL,\n  `Email` text,\n  `NormalizedEmail` varchar(85) DEFAULT
    NULL,\n  `EmailConfirmed` smallint(6) NOT NULL,\n  `PasswordHash` text,\n  `SecurityStamp`
    text,\n  `ConcurrencyStamp` text,\n  `PhoneNumber` text,\n  `PhoneNumberConfirmed`
    smallint(6) NOT NULL,\n  `TwoFactorEnabled` smallint(6) NOT NULL,\n  `LockoutEnd`
    timestamp NULL DEFAULT NULL,\n  `LockoutEnabled` smallint(6) NOT NULL,\n  `AccessFailedCount`
    int(11) NOT NULL,\n  PRIMARY KEY (`Id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client = @saved_cs_client
    */;\n\n--\n-- Table structure for table `RefreshTokens`\n--\n\nDROP TABLE IF EXISTS
    `RefreshTokens`;\n/*!40101 SET @saved_cs_client     = @@character_set_client */;\n
    SET character_set_client = utf8mb4 ;\nCREATE TABLE `RefreshTokens` (\n  `Id` int(11)
    NOT NULL AUTO_INCREMENT,\n  `Created` timestamp NOT NULL,\n  `Modified` timestamp
    NOT NULL,\n  `Token` text,\n  `Expires` timestamp NOT NULL,\n  `UserId` int(11)
    NOT NULL,\n  `RemoteIpAddress` text,\n  PRIMARY KEY (`Id`),\n  KEY `IX_RefreshTokens_UserId`
    (`UserId`),\n  CONSTRAINT `FK_RefreshTokens_Users_UserId` FOREIGN KEY (`UserId`)
    REFERENCES `Users` (`Id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=36
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Table structure for table `Users`\n--\n\nDROP
    TABLE IF EXISTS `Users`;\n/*!40101 SET @saved_cs_client     = @@character_set_client
    */;\n SET character_set_client = utf8mb4 ;\nCREATE TABLE `Users` (\n  `Id` int(11)
    NOT NULL AUTO_INCREMENT,\n  `Created` timestamp NOT NULL,\n  `Modified` timestamp
    NOT NULL,\n  `FirstName` text,\n  `LastName` text,\n  `IdentityId` text,\n  `UserName`
    text,\n  PRIMARY KEY (`Id`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client = @saved_cs_client
    */;\n\n--\n-- Table structure for table `__EFMigrationsHistory`\n--\n\nDROP TABLE
    IF EXISTS `__EFMigrationsHistory`;\n/*!40101 SET @saved_cs_client     = @@character_set_client
    */;\n SET character_set_client = utf8mb4 ;\nCREATE TABLE `__EFMigrationsHistory`
    (\n  `MigrationId` varchar(150) NOT NULL,\n  `ProductVersion` varchar(32) NOT
    NULL,\n  PRIMARY KEY (`MigrationId`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client = @saved_cs_client
    */;\n/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;\n\n/*!40101 SET SQL_MODE=@OLD_SQL_MODE
    */;\n/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;\n/*!40014 SET
    UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;\n/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT
    */;\n/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n/*!40101
    SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES
    */;\n\n-- Dump completed on 2019-06-16 19:30:27\n"
