apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-cluster-init
  labels:
    app: rabbitmq-init
    component: rabbitmq
spec:
#  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: rabbitmq-cluster-init-job
        image: khteh/rabbitmq-cluster-init:latest
        env:
          - name: RABBITMQ_ERLANG_COOKIE
            value: "mycookie"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/rabbitmq
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-config
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf
            - key: enabled_plugins
              path: enabled_plugins
