apiVersion: v1
kind: Service 
metadata:
  name: svc-elasticsearch
  labels: 
    component: elasticsearch
    app: app-elasticsearch
    role: data
spec:
  selector:
    component: elasticsearch
    app: app-elasticsearch
    role: data
  ports:  
  - port: 9200
    name: http
  - port: 9300
    name: transport
  clusterIP: None # Headless
