apiVersion: v1
kind: Service
metadata:
  name: svc-elasticsearch-discovery
  labels:
    component: elasticsearch
    app: app-elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    app: app-elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
