apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2019-07-23T08:40:31Z"
  name: biz4x-secret
  namespace: default
  resourceVersion: "144365"
  selfLink: /api/v1/namespaces/default/secrets/biz4x-secret
  uid: 87f0d577-ad25-11e9-901d-068586ff27d8
type: Opaque
data:
  biz4x-secret.json: ewogICAgIkJhY2tlbmRTZXJ2ZXJVcmwiOiAiaHR0cDovL3N2Yy1iaXo0eGJhY2tlbmQ6NTAwMiIsCiAgICAiQ29ubmVjdGlvblN0cmluZ3MiOiB7CiAgICAgICAgIkRlZmF1bHRDb25uZWN0aW9uIjogIlNlcnZlcj1iaXo0eC5jaWh2eGI0ejZuOHAuYXAtc291dGhlYXN0LTEucmRzLmFtYXpvbmF3cy5jb207RGF0YWJhc2U9Yml6NHhkYjt1c2VyPWd1ZXN0O3Bhc3N3b3JkPTR4TGFicy5jb207Y2hhcnNldD11dGY4O1BvcnQ9MzMwNjtEZWZhdWx0IENvbW1hbmQgVGltZW91dD0zMDA7IiwKICAgICAgICAiR2V0NHhDb25uZWN0aW9uIjogIlNlcnZlcj1iaXo0eC5jaWh2eGI0ejZuOHAuYXAtc291dGhlYXN0LTEucmRzLmFtYXpvbmF3cy5jb207RGF0YWJhc2U9Z2V0NHgtMTYwOTA4O3VzZXI9Z3Vlc3Q7cGFzc3dvcmQ9NHhMYWJzLmNvbTtjaGFyc2V0PXV0Zjg7UG9ydD0zMzA2O0RlZmF1bHQgQ29tbWFuZCBUaW1lb3V0PTMwMDsiLAogICAgICAgICJMb2dEYkNvbm5lY3Rpb24iOiAiU2VydmVyPWJpejR4LmNpaHZ4YjR6Nm44cC5hcC1zb3V0aGVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtEYXRhYmFzZT1iaXo0eF9kZXZfbG9nO3VzZXI9Z3Vlc3Q7cGFzc3dvcmQ9NHhMYWJzLmNvbTtjaGFyc2V0PXV0Zjg7UG9ydD0zMzA2O0RlZmF1bHQgQ29tbWFuZCBUaW1lb3V0PTMwMDsiCiAgICB9LAogICAgIlJlZGlzQ2FjaGUiOiB7CiAgICAgICAgIkNvbm5lY3Rpb24iOiAic3ZjLXJlZGlzLWNsdXN0ZXIiLAogICAgICAgICJJbnN0YW5jZU5hbWUiOiAiQml6NHhSZWRpcyIKICAgIH0KfQo=
